# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab4/Basys3_Master.xdc

# IP: ip/mmhard/mmhard.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmhard || ORIG_REF_NAME==mmhard} -quiet] -quiet
