# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab5/Basys3_Master.xdc

# IP: ip/part_3_mult/part_3_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==part_3_mult || ORIG_REF_NAME==part_3_mult} -quiet] -quiet
