@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 20 19:38:07 -0500 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_lab4dpath_time_impl -key {Post-Implementation:sim_1:Timing:tb_lab4dpath} -tclbatch tb_lab4dpath.tcl -view C:/ece4743/Lab4_part2/tb_lab4dpath_time_impl.wcfg -log simulate.log"
call xsim  tb_lab4dpath_time_impl -key {Post-Implementation:sim_1:Timing:tb_lab4dpath} -tclbatch tb_lab4dpath.tcl -view C:/ece4743/Lab4_part2/tb_lab4dpath_time_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
