# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/multiply/multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet
